Requerimientos/Procesos/Levantamiento de Requerimientos.md
=> Update Levantamiento de Requerimientos.md

Configuracion/Version Roles.md
Se actualizo los roles de libelula
=> Update roles libelulas

ProcesoCierreIteración.md
Necesidad para poder concluir la iteración.
=> Creación del proceso de cierre de iteración

README.md
=> Actualizar mapa de procesos y bitácora

Trata de Team Members.md
Proceso para evaluar una posible rotación entre los team members de los equipos de desarrollo.
=> Create Trata de Team Members.md

Planificacion/Procesos/PlanIteración.md
Cambiar diagrama por tabla, estándares del departamento.
=> Actualizar fases del proceso

README.md
Para que sea más claro nuestro mapa de procesos.
=> Mejorar mapa de procesos

Requerimientos/Procesos/Levantamiento de Requerimientos.md
Se actualizo 2.0 levantamiento de requerimientos
=> Requerimientos

README.md
Agregar proceso de definición de métricas al mapa de procesos.
=> Agregar proceso al mapa.

Planificacion/Plan/Plan auditoría planeación 06 abril.csv, Planificacion/Plan/Retroalimentación.md
Empezar a documentar planes que se crean en el dpto y su respectiva retroalimentación.
=> Danielamezcua patch 1

Configuracion/Procesos/Proceso Versionar.md
Se agregó la parte de repositorio de métricas y la fase de análisis de métricas @valternunez
=> Update Proceso Versionar.md

Configuracion/Procesos/Proceso Cambios.md
Se agregó los cambios realizados al proceso de procesos @valternunez
=> Update Proceso Cambios.md

MA/Metricas.md
=> Actualizar documentos de estatus

Procesos.md
=> Mejora del proceso

MA/Metricas.md
Agregar bitácora y repositorios físicos
=> Actualizar

README.md
Link para mi proceso de auditorias
=> Link en Proceso Generales

Requerimientos/Procesos/Mantenimiento de Requerimientos.md
=> Update Mantenimiento de Requerimientos.md

Configuracion/Procesos/Proceso Versionar.md
Se modificó la redacción de las métricas porque no era entendible haciendo que las métricas fueran ambiguas
=> Modificar la redacción.md

Arquitectura/Manuales/Manual Arquitectura General.md
Agregar pasos para configurar HTTPS en el servidor
=> Agregar documentación para configurar HTTPS

Validacion/Proceso de Validación.md
Optimizar el proceso para eficientizar los tiempos de llenado
=> Update Proceso de Validación.md

Arquitectura/Manuales/Manual Arquitectura General.md
Configuración del dominio y redirigir subdominio www al dominio raíz con Nginx
=> Agregar configuración del dominio

README.md
Se corrigió el Readme por un error en el markdown
=> Corregir-Readme

SWAT/ReporteSWAT.md
=> Error de escritura

Guia Wiki.md
Se actualizó la guía ya que había una sección que ya no era necesaria gracias al mapa de procesos
=> Update Guia Wiki.md

Configuracion/Guias/Guia Configuration Item.md
Se actualizó la línea base para que pudiera tener los elemenentos más actualizados
=> Update Guia Configuration Item.md

Calidad/Politicas Calidad.md, Calidad/Politicas Generales/Politicas Formatos.md, Calidad/Politicas Generales/Politicas Politicas.md
Se agregó el documento de políticas de calidad para las políticas de calidad
=> Create Politicas Politicas.md

Configuracion/Guias/Guia Herramientas.md
Se corrigió un error de ortografía
=> Update Guia Herramientas.md

Calidad/Politicas Generales/Politicas Guias.md
=> Update Politicas Guias.md

PMC/Proceso de Reporte de Estatus.md
Mejora al proceso, ahora se incluyen todos los stakeholders a la hora de hacer reporte de estatus.
=> Mejora a Reporte de Estatus

Gestion Personas/Procesos/Proceso Roles.md
=> Update Proceso Roles.md

Configuracion/Version Roles.md
Errores ortográficos y en viñetas
=> Update Version Roles.md

Auditorias.md
Agregar auditoría del 2 de mayo de MA
=> Agregar auditoría MA

Configuracion/Versiones Herramientas.md
=> Update Versiones Herramientas.md

SWAT/Guias/GuiaMetricaSWAT.md
Se hizo la correción de la guia para cumplir con los estandares del departamento
=> Correcion de la guía para estandares

Planificacion/Plan/Retroalimentación.md, Planificacion/Procesos/Planificacion.md
Estimado encargado de Procesos: 
Aprovecho la ocasión para enviarle un caluroso saludo.
Si es que mi humilde proceso cumple con sus expectativas le pido que agregue su aprobación en la bitácora. 
Saludos.
=> Danielamezcua actualizar proceso planificacion

Usabilidad/Guias/Usabilidad.md
Cambiar a carpeta de Guias y agregar la bitácora de última edición.
=> Cambiar ubicación y agregar bitácora

Gestion Personas/Procesos/Proceso Roles.md
=> Cambio de versión

Mejora Procesos/Procesos/Mejora Procesos.md
Añadir mejora al proceso de mejora de procesos
=> Update Mejora Procesos.md

Gestion Personas/Procesos/Proceso Roles.md
=> Cambiar criterios de entrada y entrada del proceso

Riesgos/Procesos/Plan_de_Riesgos.md
Actualizada segun la nueva plantilla de creacion de procesos para completar los campos faltantes.
=> Actualizar Proceso de plan de riesgos

Mejora Procesos/Procesos/Mejora Procesos.md
Cambiar link en mejora de procesos
=> Cambiar link en mejora de procesos

README.md
Se cambió la liga porque no funcionaba
=> Cambiar liga de mejora de procesos en README.md

Auditorias.md
Agregar los resultados de las auditorías de Kanban realizadas el 3 de mayo de 2018.
=> Agregar auditoría de Kanban

Gestion Personas/Procesos/Trata Team Members.md
Cambio al proceso de acuerdo con la mejora de procesos
=> Mh siles/trata tm

Procesos.md
En un error de dedo se nos pasó un gramaticamente, corregido.
=> Corrección de ortigrafía

MA/Metricas.md
Incluir transición en los repositorios de CADHU.
=> Actualizar repositorios

Configuracion/Version Roles.md
Verificación de calidad con checklist.
=> Verificación de calidad

Planificacion/Procesos/Guía Estimación.md
Update de la guía de estimación Faltan las imágenes, Melannie las agregará.
=> Create Guía Estimación.md

Arquitectura/Procesos/Definición de Componentes del Sistema.md
Se cambió el proceso para que vaya de acuerdo al proceso de procesos
=> Update Definición de Componentes del Sistema.md

Arquitectura/Procesos/Definición de Arquitectura Inicial.md
Se cambió el proceso para que vaya de acuerdo al proceso de procesos
=> Update Definición de Arquitectura Inicial.md

Minutas.md
Hice los cambios en minutas que pidió la CM
=> Update README de Minutas

Riesgos/Procesos/Plan_de_Riesgos.md
El url no funcionaba, ya lo corregí
=> Corregir url de riesgos

Arquitectura/Procesos/Definición de Flujo de Vistas.md
el link roto se debía al paso des actualizado así que fue borrado
=> Eliminar paso desactualizado
